# yaml-language-server: $schema=https://raw.githubusercontent.com/ast-grep/ast-grep/main/schemas/sgconfig.json

ruleDirs:
  - rules/shared
  - rules/effect

testConfigs:
  - testDir: rule-tests/shared
  - testDir: rule-tests/effect

languageGlobs:
  tsx: ["*.ts", "*.tsx"]
